mcc -win32 -W cpplib:MatLib -T link:lib ...
    ImplElec_Test.m ...
    ImplElec_Train.m ...
    SaveCapturedData.m ...
    Entry_Train.m ...
    Entry_Test.m ...
    Mat_ECOG_Test.m ...
    Mat_ECOG_Train.m
